version: "3"

services:
  api:
    build: .
    ports:
      - "9001:9001"
    depends_on: 
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: marreco
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: stock
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'  

volumes:
  app_data:
  db_data:
